# Generated by Django 4.2.16 on 2024-10-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=150, null=True)),
                ("job_data", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("Assigned", "Assigned"),
                            ("Running", "Running"),
                            ("Break", "Break"),
                            ("Finished", "Finished"),
                        ],
                        default="Assigned",
                        max_length=10,
                    ),
                ),
                ("job_time", models.TimeField(blank=True, null=True)),
                ("job_date", models.DateField(blank=True, null=True)),
                (
                    "job_duration",
                    models.DurationField(
                        blank=True, help_text="Example: 1:2 for 1 hr 2 mins", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="fleet.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "form_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="general.jobformfield",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("arrive_job", "Arrive Job"),
                            ("arrive_site", "Arrive Site"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_image",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
    ]
