# Generated by Django 4.2.16 on 2024-10-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_jobformfield_field_type'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='general.jobformfield')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='jobs.job')),
            ],
        ),
    ]
