# Generated by Django 4.2.16 on 2024-10-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_jobinfo_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="finish_reason",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="jobimage",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("arrive_job", "Arrive Job"),
                    ("arrive_site", "Arrive Site"),
                    ("finish_job", "Finish Job"),
                ],
                max_length=11,
            ),
        ),
    ]
