# Generated by Django 4.2.16 on 2024-10-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_initial"),
        ("general", "0004_alter_contactus_options"),
        ("jobs", "0003_job_finish_reason_alter_jobimage_action_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrefillChecks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefill_checks",
                        to="fleet.driver",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefill_checks",
                        to="general.jobformfield",
                    ),
                ),
            ],
        ),
    ]
