# Generated by Django 4.2.16 on 2025-02-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefillchecks',
            options={'verbose_name_plural': 'Prefill Checks'},
        ),
        migrations.AddField(
            model_name='job',
            name='filled_pdf',
            field=models.FileField(blank=True, null=True, upload_to='filled_pdf/'),
        ),
    ]
