# Generated by Django 4.2.16 on 2025-05-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_prefillchecks_options_job_filled_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="departed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
