# Generated by Django 4.2.16 on 2024-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_job_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_time',
            field=models.DurationField(blank=True, help_text='1:2 for 1 hr 2 mins', null=True),
        ),
    ]
