# Generated by Django 4.2.16 on 2025-05-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_job_departed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobimage",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
