# Generated by Django 4.2.16 on 2025-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobimage_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='arrived_job_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='arrived_site_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
