# Generated by Django 4.2.16 on 2024-10-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_vehicle_driver'),
        ('jobs', '0009_jobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_duration',
            field=models.DurationField(blank=True, help_text='Example: 1:2 for 1 hr 2 mins', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='fleet.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
