# Generated by Django 4.2.16 on 2024-10-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_remove_vehicle_driver'),
        ('general', '0002_alter_jobformfield_field_type'),
        ('jobs', '0010_job_job_duration_job_vehicle_alter_job_job_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='general.jobformfield'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.job'),
        ),
    ]
