# Generated by Django 4.2.16 on 2024-10-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_driver_alter_jobimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
