# Generated by Django 4.2.16 on 2024-10-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_remove_vehicle_driver'),
        ('jobs', '0012_alter_jobimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_time',
        ),
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Running', 'Running'), ('Break', 'Break'), ('Finished', 'Finished')], default='Assigned', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.vehicle'),
        ),
    ]
