# Generated by Django 4.2.16 on 2024-10-12 13:47

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_id",
                    models.CharField(
                        default=fleet.models.generate_driver_id,
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("license_number", models.CharField(max_length=12)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Flatbed Trucks", "Flatbed Trucks"),
                            ("Tail-Lift Trucks", "Tail-Lift Trucks"),
                            ("Box Trucks", "Box Trucks"),
                            ("Dump Trucks", "Dump Trucks"),
                            ("Semi-Trailer Trucks", "Semi-Trailer Trucks"),
                            ("Jumbo Trailer Trucks", "Jumbo Trailer Trucks"),
                            ("Tanker Trucks", "Tanker Trucks"),
                            ("Refrigerated Trucks", "Refrigerated Trucks"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("plate_number", models.CharField(max_length=10)),
            ],
        ),
    ]
