# Generated by Django 4.2.16 on 2024-10-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_vehicle_name_vehicle_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Flatbed Trucks', 'Flatbed Trucks'), ('Tail-Lift Trucks', 'Tail-Lift Trucks'), ('Box Trucks', 'Box Trucks'), ('Dump Trucks', 'Dump Trucks'), ('Semi-Trailer Trucks', 'Semi-Trailer Trucks'), ('Jumbo Trailer Trucks', 'Jumbo Trailer Trucks'), ('Tanker Trucks', 'Tanker Trucks'), ('Refrigerated Trucks', 'Refrigerated Trucks')], max_length=100, null=True),
        ),
    ]
