# Generated by Django 4.2.16 on 2024-10-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
    ]
