# Generated by Django 4.2.16 on 2024-10-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobformfield',
            name='field_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Boolean', 'Boolean'), ('Select', 'Select')], max_length=50),
        ),
    ]
