# Generated by Django 4.2.16 on 2024-10-15 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_supportperson_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
