# Generated by Django 4.2.16 on 2024-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_jobformfield_use_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobformfield",
            name="use_case",
            field=models.CharField(
                choices=[
                    ("start_day", "Start Day"),
                    ("finish_job", "Finish Job"),
                    ("finish_day", "Finish Day"),
                ],
                default="start_day",
                max_length=50,
            ),
        ),
    ]
