# Generated by Django 4.2.16 on 2024-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_jobformfield_use_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportperson',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='support_person/'),
        ),
    ]
