# Generated by Django 4.2.16 on 2024-10-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_supportperson_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='ContactUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_us/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_image', to='general.contactus')),
            ],
        ),
    ]
