# Generated by Django 4.2.16 on 2025-02-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_contactus_contact_number_contactusimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobformfield',
            options={'verbose_name': 'Job Pre-fill Check', 'verbose_name_plural': 'Job Pre-fill Checks'},
        ),
    ]
